//
// Created by dedus on 07.02.2026.
//

#ifndef GLADEMAGE_EXAM_SLASHING_LUNGE_SWORDMAN_H
#define GLADEMAGE_EXAM_SLASHING_LUNGE_SWORDMAN_H


class Slashing_Lunge_SwordMan {
};


#endif //GLADEMAGE_EXAM_SLASHING_LUNGE_SWORDMAN_H